ALTER TABLE LOG DROP CONSTRAINT FK_LOG_MACHINE_ID
ALTER TABLE MACHINE_LOG DROP CONSTRAINT MACHINE_LOGlogs_ID
ALTER TABLE MACHINE_LOG DROP CONSTRAINT MCHINELOGMachineID
DROP TABLE LOG
DROP TABLE MACHINE
DROP TABLE MACHINE_LOG
