// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package srcs.chat;

public interface NewMessageRecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.chat.NewMessageRec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pseudo_expediteur = 1;</code>
   */
  java.lang.String getPseudoExpediteur();
  /**
   * <code>string pseudo_expediteur = 1;</code>
   */
  com.google.protobuf.ByteString
      getPseudoExpediteurBytes();

  /**
   * <code>string contenu = 2;</code>
   */
  java.lang.String getContenu();
  /**
   * <code>string contenu = 2;</code>
   */
  com.google.protobuf.ByteString
      getContenuBytes();
}
