// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapRem.proto

package srcs.map;

public final class MapRem {
  private MapRem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_map_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_map_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014mapRem.proto\022\010srcs.map\032\033google/protobu" +
      "f/empty.proto\032\031google/protobuf/any.proto" +
      "\"O\n\005Entry\022!\n\003key\030\001 \001(\0132\024.google.protobuf" +
      ".Any\022#\n\005value\030\002 \001(\0132\024.google.protobuf.An" +
      "y2n\n\tMapRemote\0221\n\003get\022\024.google.protobuf." +
      "Any\032\024.google.protobuf.Any\022.\n\003put\022\017.srcs." +
      "map.Entry\032\026.google.protobuf.EmptyB\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_srcs_map_Entry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_srcs_map_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_map_Entry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
