// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapStringRem.proto

package srcs.map;

public final class MapStringRem {
  private MapStringRem() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_map_EntryString_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_map_EntryString_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022mapStringRem.proto\022\010srcs.map\032\033google/p" +
      "rotobuf/empty.proto\032\036google/protobuf/wra" +
      "ppers.proto\")\n\013EntryString\022\013\n\003key\030\001 \001(\t\022" +
      "\r\n\005value\030\002 \001(\t2\212\001\n\017MapStringRemote\022A\n\003ge" +
      "t\022\034.google.protobuf.StringValue\032\034.google" +
      ".protobuf.StringValue\0224\n\003put\022\025.srcs.map." +
      "EntryString\032\026.google.protobuf.EmptyB\002P\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_srcs_map_EntryString_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_srcs_map_EntryString_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_map_EntryString_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
